# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publishable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('routing_key', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('headers', models.TextField(blank=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
